/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.interfaces_graficas;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.patron_proxy.ServidorBD;
import src.users.Empleado;

/**
 *
 * @author Carlos
 */
public class BuscarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form BuscarEmpleado
     */
    ServidorBD sbd = new ServidorBD();

    public BuscarEmpleado() {
        initComponents();
    }

    public String getDNIBusqueda() {

        return jTextFieldDniIntroducido.getText();
    }

    public String getNombreBusqueda() {

        return jTextFieldNombreIntroducido.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonModificacionDatosEmpleado = new javax.swing.JButton();
        jButtonEliminarElementoSeleccionado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonVolverAtrasBuscarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMuestraEmpleados = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jButtonBusquedaDNI = new javax.swing.JButton();
        jTextFieldDniIntroducido = new javax.swing.JTextField();
        jButtonBusquedaNombre = new javax.swing.JButton();
        jTextFieldNombreIntroducido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonModificacionDatosEmpleado.setBackground(new java.awt.Color(255, 153, 0));
        jButtonModificacionDatosEmpleado.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonModificacionDatosEmpleado.setText("Modificar");
        jButtonModificacionDatosEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificacionDatosEmpleadoActionPerformed(evt);
            }
        });

        jButtonEliminarElementoSeleccionado.setBackground(new java.awt.Color(255, 0, 0));
        jButtonEliminarElementoSeleccionado.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButtonEliminarElementoSeleccionado.setText("Eliminar");
        jButtonEliminarElementoSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarElementoSeleccionadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("DNI");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jButtonVolverAtrasBuscarEmpleado.setBackground(new java.awt.Color(255, 102, 102));
        jButtonVolverAtrasBuscarEmpleado.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonVolverAtrasBuscarEmpleado.setText("Atrás");

        jTableMuestraEmpleados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableMuestraEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Apellidos", "Correo", "Password", "Horario", "Telefono", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMuestraEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMuestraEmpleados);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 255));
        jLabel24.setText("Búsqueda de empleado");

        jButtonBusquedaDNI.setBackground(new java.awt.Color(0, 102, 255));
        jButtonBusquedaDNI.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonBusquedaDNI.setText("Buscar ");
        jButtonBusquedaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaDNIActionPerformed(evt);
            }
        });

        jTextFieldDniIntroducido.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButtonBusquedaNombre.setBackground(new java.awt.Color(0, 102, 255));
        jButtonBusquedaNombre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonBusquedaNombre.setText("Buscar ");
        jButtonBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaNombreActionPerformed(evt);
            }
        });

        jTextFieldNombreIntroducido.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonVolverAtrasBuscarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDniIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonBusquedaDNI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel3))
                            .addComponent(jTextFieldNombreIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBusquedaNombre)
                        .addGap(99, 99, 99)))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonModificacionDatosEmpleado)
                        .addGap(182, 182, 182)
                        .addComponent(jButtonEliminarElementoSeleccionado)
                        .addGap(181, 181, 181))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDniIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificacionDatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarElementoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVolverAtrasBuscarEmpleado))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(351, 351, 351))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBusquedaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaDNIActionPerformed

        ArrayList<Empleado> list = sbd.consultagetEmpleadosDNI(getDNIBusqueda());
        DefaultTableModel tablaMuestra = (DefaultTableModel) jTableMuestraEmpleados.getModel();
        tablaMuestra.setRowCount(0); // para que no se repita los resultados al pulsar al buscar

        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getDni();
            row[1] = list.get(i).getNombre();
            row[2] = list.get(i).getApellidos();
            row[3] = list.get(i).getCorreo();
            row[4] = list.get(i).getPassword();
            row[5] = list.get(i).getHorario();
            row[6] = list.get(i).getTelefono();
            row[7] = list.get(i).getCategoria();

            tablaMuestra.addRow(row);
        }


    }//GEN-LAST:event_jButtonBusquedaDNIActionPerformed

    private void jButtonModificacionDatosEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificacionDatosEmpleadoActionPerformed
        DefaultTableModel tablaMuestra = (DefaultTableModel) jTableMuestraEmpleados.getModel();
        int indiceFilaSeleccionada = jTableMuestraEmpleados.getSelectedRow();

        ModificacionDatosEmpleado mde = new ModificacionDatosEmpleado();

        if (indiceFilaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            String nuevoDniModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 0).toString();
            String nuevoNombreModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 1).toString();
            String nuevoApellidosModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 2).toString();
            String nuevoCorreoModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 3).toString();
            String nuevoPasswordModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 4).toString();
            String nuevoHorarioModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 5).toString();
            String nuevoTelefonoModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 6).toString();
            String nuevaCategoriaModificar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 7).toString();

            if (indiceFilaSeleccionada != -1) {
                mde.jTextFieldDniAModificar.setText(nuevoDniModificar);
                mde.jTextFieldNombreAModificar.setText(nuevoNombreModificar);
                mde.jTextFieldApellidosAModificar.setText(nuevoApellidosModificar);
                mde.jTextFieldCorreoAModificar.setText(nuevoCorreoModificar);
                mde.jTextFieldContraseñaAModificar.setText(nuevoPasswordModificar);
                mde.jTextFieldHorarioAModificar.setText(nuevoHorarioModificar);
                mde.jTextFieldTelefonoAModificar.setText(nuevoTelefonoModificar);
                mde.jTextFieldCategoriaAModificar.setText(nuevaCategoriaModificar);

                mde.setVisible(true);
                mde.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificacionDatosEmpleadoActionPerformed

    private void jButtonBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaNombreActionPerformed
        // TODO add your handling code here:
        ArrayList<Empleado> list = sbd.consultagetEmpleadosNombre(getNombreBusqueda());
        DefaultTableModel tablaMuestra = (DefaultTableModel) jTableMuestraEmpleados.getModel();
        tablaMuestra.setRowCount(0);
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getDni();
            row[1] = list.get(i).getNombre();
            row[2] = list.get(i).getApellidos();
            row[3] = list.get(i).getCorreo();
            row[4] = list.get(i).getPassword();
            row[5] = list.get(i).getHorario();
            row[6] = list.get(i).getTelefono();
            row[7] = list.get(i).getCategoria();
            tablaMuestra.addRow(row);
        }

    }//GEN-LAST:event_jButtonBusquedaNombreActionPerformed

    private void jButtonEliminarElementoSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarElementoSeleccionadoActionPerformed

        ArrayList<Empleado> list = sbd.consultagetEmpleadosNombre(getNombreBusqueda());
        DefaultTableModel tablaMuestra = (DefaultTableModel) jTableMuestraEmpleados.getModel();
        int indiceFilaSeleccionada = jTableMuestraEmpleados.getSelectedRow();

        if (indiceFilaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            String dniEliminar = tablaMuestra.getValueAt(indiceFilaSeleccionada, 0).toString();
            System.out.println(dniEliminar);
            sbd.eliminarEmpleado(dniEliminar);

            tablaMuestra.removeRow(indiceFilaSeleccionada);
        }


    }//GEN-LAST:event_jButtonEliminarElementoSeleccionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBusquedaDNI;
    private javax.swing.JButton jButtonBusquedaNombre;
    private javax.swing.JButton jButtonEliminarElementoSeleccionado;
    private javax.swing.JButton jButtonModificacionDatosEmpleado;
    private javax.swing.JButton jButtonVolverAtrasBuscarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMuestraEmpleados;
    private javax.swing.JTextField jTextFieldDniIntroducido;
    private javax.swing.JTextField jTextFieldNombreIntroducido;
    // End of variables declaration//GEN-END:variables
}
