/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.interfaces_graficas;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import src.Validaciones;
import src.fachada.FachadaAdminSRP;
import src.patron_factory_method_productos.Categoria;
import src.patron_factory_method_productos.FabricaCategoria;
import src.patron_factory_method_productos.Producto;
import src.patron_proxy.ProxyGestorBD;

/**
 *
 * @author Carlos
 */
public class RegistrarProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEmpleado
     */
    private FachadaAdminSRP fachada = new FachadaAdminSRP();
    private ProxyGestorBD sbd = ProxyGestorBD.getInstancia();

    private FabricaCategoria fcat = new FabricaCategoria();

    private HomeAdmin ha;

    public RegistrarProducto(HomeAdmin HA) {
        initComponents();
        setTitle("Busqueda de Productos");
        this.ha = HA;
        setLocationRelativeTo(null);
    }

    public String getIdProductoregistrar() {
        return jTextFieldIdProductoARegistrar.getText();
    }

    public String getCategoriaProductoARegistrar() {
        return (String) jComboBoxCategoriaARegistrarProducto.getSelectedItem();
    }

    public String getNombreProductoRegistrar() {
        return jTextFieldNombreProductoARegistrar.getText();
    }

    public String getMarcaProductoRegistrar() {
        return jTextFieldMarcaProductoARegistrar.getText();
    }

    public String getPrecioProductoRegistrar() {
        return jTextFieldPrecioProductoARegistrar.getText();
    }

    public String getUnidadesProductoRegistrar() {
        return jTextFieldUnidadesARegistrar.getText();
    }

    public String getProcedenciaProductoRegistrar() {
        return jTextFieldProcedenciaARegistrar.getText();
    }

    public String getFechaLlegadaProductoRegistrar() {
        return jTextFieldFechaLlegadaARegistrar.getText();
    }

    public String getFechaCaducidadProductoRegistrar() {
        return jTextFieldFechaCaducidadARegistrar.getText();
    }

    public String getLocalizacionProductoRegistrar() {
        return jTextFieldFechaLocalizacionARegistrar.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdProductoAModificar = new javax.swing.JTextField();
        jTextFieldSubcategoriaAModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProcedenciaAModificar = new javax.swing.JTextField();
        jTextFieldUnidadesAModificar = new javax.swing.JTextField();
        jTextFieldFechaCaducidadAModificar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCategoriaAModificar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFechaLocalizacionAModificar = new javax.swing.JTextField();
        jTextFieldMarcaAModificar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPrecioAModificar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFechaLlegadaAModificar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNombreModificar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonVolverAtrasRegistrarEmpleado = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldIdProductoARegistrar = new javax.swing.JTextField();
        jTextFieldNombreProductoARegistrar = new javax.swing.JTextField();
        jTextFieldMarcaProductoARegistrar = new javax.swing.JTextField();
        jTextFieldPrecioProductoARegistrar = new javax.swing.JTextField();
        jTextFieldUnidadesARegistrar = new javax.swing.JTextField();
        jTextFieldProcedenciaARegistrar = new javax.swing.JTextField();
        jTextFieldFechaLlegadaARegistrar = new javax.swing.JTextField();
        jTextFieldFechaCaducidadARegistrar = new javax.swing.JTextField();
        jTextFieldFechaLocalizacionARegistrar = new javax.swing.JTextField();
        jButtonRegistrarDatosProducto = new javax.swing.JButton();
        jComboBoxCategoriaARegistrarProducto = new javax.swing.JComboBox<>();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Subcategoría");

        jTextFieldIdProductoAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldSubcategoriaAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Procedencia");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Id del producto");

        jTextFieldProcedenciaAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldUnidadesAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldFechaCaducidadAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Unidades");

        jTextFieldCategoriaAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Fecha de llegada");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nombre");

        jTextFieldFechaLocalizacionAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldMarcaAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Precio");

        jTextFieldPrecioAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Marca");

        jTextFieldFechaLlegadaAModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fecha de caducidad");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Categoría");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Localizacion");

        jTextFieldNombreModificar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVolverAtrasRegistrarEmpleado.setBackground(new java.awt.Color(255, 102, 102));
        jButtonVolverAtrasRegistrarEmpleado.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonVolverAtrasRegistrarEmpleado.setText("Atrás");
        jButtonVolverAtrasRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasRegistrarEmpleadoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Localizacion");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Fecha de caducidad");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Fecha de llegada");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Procedencia");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Unidades");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Precio");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Marca");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Categoría");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Id del producto");

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 255));
        jLabel24.setText("Registro de producto");

        jTextFieldIdProductoARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldNombreProductoARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldMarcaProductoARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldPrecioProductoARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldUnidadesARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldProcedenciaARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldFechaLlegadaARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldFechaCaducidadARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldFechaLocalizacionARegistrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButtonRegistrarDatosProducto.setBackground(new java.awt.Color(51, 153, 0));
        jButtonRegistrarDatosProducto.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonRegistrarDatosProducto.setText("Insertar");
        jButtonRegistrarDatosProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarDatosProductoActionPerformed(evt);
            }
        });

        jComboBoxCategoriaARegistrarProducto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBoxCategoriaARegistrarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verduras", "Frutas", "Pescado", "Carne", "Pollo", "Embutidos", "Lacteos", "Dulces", "Bebidas", "Especias", "Salsas ", "Pasta ", "Snacks ", "Postres", "Otros ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVolverAtrasRegistrarEmpleado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUnidadesARegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPrecioProductoARegistrar)
                                    .addComponent(jTextFieldNombreProductoARegistrar)
                                    .addComponent(jTextFieldMarcaProductoARegistrar)
                                    .addComponent(jTextFieldProcedenciaARegistrar)
                                    .addComponent(jTextFieldIdProductoARegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCategoriaARegistrarProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldFechaCaducidadARegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFechaLlegadaARegistrar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFechaLocalizacionARegistrar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdProductoARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCategoriaARegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreProductoARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarcaProductoARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecioProductoARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnidadesARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProcedenciaARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFechaLlegadaARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFechaCaducidadARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaLocalizacionARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolverAtrasRegistrarEmpleado))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasRegistrarEmpleadoActionPerformed
        this.setVisible(false);
        ha.setVisible(true);
    }//GEN-LAST:event_jButtonVolverAtrasRegistrarEmpleadoActionPerformed

    private void jButtonRegistrarDatosProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarDatosProductoActionPerformed

        DateFormat forma = new SimpleDateFormat("yyyy" + '-' + "MM" + '-' + "dd");
        Date fechaCaducidadParseada, fechaLlegadaParseada, fechaActualParseada;

        ArrayList<String> listaIdsProducto = sbd.getIDSproductos();

        if (getIdProductoregistrar().isEmpty() || getCategoriaProductoARegistrar().isEmpty() || getNombreProductoRegistrar().isEmpty() || getMarcaProductoRegistrar().isEmpty()
                || getPrecioProductoRegistrar().isEmpty() || getUnidadesProductoRegistrar().isEmpty() || getProcedenciaProductoRegistrar().isEmpty()
                || getFechaLlegadaProductoRegistrar().isEmpty() || getFechaCaducidadProductoRegistrar().isEmpty() || getLocalizacionProductoRegistrar().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Campos vacios, rellene todos", "Error!", JOptionPane.ERROR_MESSAGE);
        } else if (listaIdsProducto.contains(getIdProductoregistrar())) {
            JOptionPane.showMessageDialog(null, "ID'S duplicados", "Error ID!", JOptionPane.ERROR_MESSAGE);
        } else if (Validaciones.validarFecha(getFechaLlegadaProductoRegistrar()) == false) {
            JOptionPane.showMessageDialog(null, "Formato Fecha llegada incorrecto", "Fecha llegada!", JOptionPane.ERROR_MESSAGE);
        } else if (Validaciones.validarFecha(getFechaCaducidadProductoRegistrar()) == false) {
            JOptionPane.showMessageDialog(null, "Formato Fecha caducidad incorrecto", "Fecha caducidad!", JOptionPane.ERROR_MESSAGE);

        } else if (Validaciones.validarSoloNumerosPrecios(getPrecioProductoRegistrar()) == false) {
            JOptionPane.showMessageDialog(null, "Solo escriba numeros decimales separado con un punto", "Precio!", JOptionPane.ERROR_MESSAGE);
        } else if (Validaciones.validarSoloNumerosUnidades(getUnidadesProductoRegistrar()) == false) {
            JOptionPane.showMessageDialog(null, "Solo escriba numeros enteros", "Unidades!", JOptionPane.ERROR_MESSAGE);

        } else {
            //Aplicacion del FactoryMethod donde se crea el objteo categoria y se inserta el empleado obteniendo el nombre de la categoria del objeto creado.

            try {
                fechaCaducidadParseada = (Date) forma.parse(getFechaCaducidadProductoRegistrar());
                fechaLlegadaParseada = (Date) forma.parse(getFechaLlegadaProductoRegistrar());
                Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
                String fechaActual = forma.format(fecha);
                int unidadesParseadas = Integer.parseInt(getUnidadesProductoRegistrar());
                fechaActualParseada = (Date) forma.parse(fechaActual);

                if (fechaLlegadaParseada.compareTo(fechaCaducidadParseada) > 0) {

                    JOptionPane.showMessageDialog(null, "La fecha de llegada tiene que ser menor O o igual que la de caducidad", "Fechas!", JOptionPane.ERROR_MESSAGE);
                } else if (fechaLlegadaParseada.compareTo(fechaActualParseada) < 0 || fechaCaducidadParseada.compareTo(fechaActualParseada) < 0) {
                    JOptionPane.showMessageDialog(null, "Las fechas tienen que ser mayores o iguales que la actual", "Fechas!", JOptionPane.ERROR_MESSAGE);

                } else if (unidadesParseadas < 0 || unidadesParseadas > 100) {

                    JOptionPane.showMessageDialog(null, "El número de unidades tiene que estar entre 0 y 100", "Unidades!", JOptionPane.ERROR_MESSAGE);

                } else {
                    Double precioDouble = Double.parseDouble(getPrecioProductoRegistrar());
                    int unidadesInt = Integer.parseInt(getUnidadesProductoRegistrar());

                    Categoria categoriaCreada = fcat.crearCategoria(getCategoriaProductoARegistrar().trim());

                    // Si la categoria concreta concuerda con la puesta se crea el objeto categoria y posteriormente el objeto producto
                    if (categoriaCreada.getNombre().equals(getCategoriaProductoARegistrar())) {
                        Producto p = new Producto(getIdProductoregistrar(), categoriaCreada.getNombre(), getNombreProductoRegistrar(), getMarcaProductoRegistrar(),
                                precioDouble, unidadesInt, getProcedenciaProductoRegistrar(),
                                getFechaLlegadaProductoRegistrar(), getFechaCaducidadProductoRegistrar(), getLocalizacionProductoRegistrar());

                        fachada.insertarProducto(p);
                        JOptionPane.showMessageDialog(null, "Producto registrado", "Correcto!", JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                        ha.setVisible(true);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButtonRegistrarDatosProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarDatosProducto;
    private javax.swing.JButton jButtonVolverAtrasRegistrarEmpleado;
    public javax.swing.JComboBox<String> jComboBoxCategoriaARegistrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCategoriaAModificar;
    private javax.swing.JTextField jTextFieldFechaCaducidadAModificar;
    private javax.swing.JTextField jTextFieldFechaCaducidadARegistrar;
    private javax.swing.JTextField jTextFieldFechaLlegadaAModificar;
    private javax.swing.JTextField jTextFieldFechaLlegadaARegistrar;
    private javax.swing.JTextField jTextFieldFechaLocalizacionAModificar;
    private javax.swing.JTextField jTextFieldFechaLocalizacionARegistrar;
    private javax.swing.JTextField jTextFieldIdProductoAModificar;
    private javax.swing.JTextField jTextFieldIdProductoARegistrar;
    private javax.swing.JTextField jTextFieldMarcaAModificar;
    private javax.swing.JTextField jTextFieldMarcaProductoARegistrar;
    private javax.swing.JTextField jTextFieldNombreModificar;
    private javax.swing.JTextField jTextFieldNombreProductoARegistrar;
    private javax.swing.JTextField jTextFieldPrecioAModificar;
    private javax.swing.JTextField jTextFieldPrecioProductoARegistrar;
    private javax.swing.JTextField jTextFieldProcedenciaAModificar;
    private javax.swing.JTextField jTextFieldProcedenciaARegistrar;
    private javax.swing.JTextField jTextFieldSubcategoriaAModificar;
    private javax.swing.JTextField jTextFieldUnidadesAModificar;
    private javax.swing.JTextField jTextFieldUnidadesARegistrar;
    // End of variables declaration//GEN-END:variables
}
