/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  cgpc2
 * Created: 08-ene-2022
 */

CREATE TABLE EMPLEADO
(DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(30)NOT NULL,
APELLIDOS VARCHAR(80) NOT NULL,
CORREO VARCHAR(80) UNIQUE NOT NULL,
PASSWORD VARCHAR(50)NOT NULL,
HORARIO VARCHAR(10)NOT NULL,
TELEFONO VARCHAR(9)NOT NULL,
CATEGORIA VARCHAR(30)NOT NULL,

PRIMARY KEY (DNI)
);

CREATE TABLE ADMINISTRADOR

(
DNI_EMPLEADO VARCHAR(9)NOT NULL,

FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO (DNI) ON DELETE CASCADE
);


CREATE TABLE PRODUCTO
(ID_PRODUCTO VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(30)NOT NULL,
NOMBRE VARCHAR(80)NOT NULL,
MARCA VARCHAR(50)NOT NULL,
PRECIO DOUBLE NOT NULL,
UNIDADES INTEGER NOT NULL,
PROCEDENCIA VARCHAR(40)NOT NULL,
FECHA_LLEGADA VARCHAR(40) NOT NULL,
FECHA_CADUCIDAD VARCHAR(40) NOT NULL,
LOCALIZACION VARCHAR(40)NOT NULL,
PRIMARY KEY (ID_PRODUCTO)
);


CREATE TABLE EMPLEADO_PRODUCTOS

(ID_PRODUCTO VARCHAR(50) NOT NULL,
DNI_EMPLEADO VARCHAR(9)NOT NULL,
UNIDADES INTEGER NOT NULL,
HORA_MODIFICACION TIMESTAMP NOT NULL,

    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE CASCADE,
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO (DNI) ON DELETE CASCADE  
 


);
